# ==========================================================
# RonPaulCoin (RPC) Network Configuration
# ==========================================================

# Network & Daemon Options
listen=1
daemon=1
server=1
maxconnections=32
dbcache=25

# P2P & RPC Ports
port=9027
rpcport=9026
rpcallowip=127.0.0.1

# Generic RPC Credentials (change for local mining / scripts)
rpcuser=ronpaulcoinrpc
rpcpassword=ReplaceWithYourOwnPassword1776

# ==========================================================
# Active Network Seed Nodes
# ==========================================================
# Community Seed Node (Chicago, USA)
addnode=realtrueog.com:9027

# Fallback Seed Node (Russia)
addnode=91.206.16.214:9027
